#!/bin/sh
#################################################################
#
#   mk_ucsf_legacy_rewrite_rules.sh
#   
#   This script generates an apache configuration file for mod_rewrite
#   on the UCSF.edu web servers,
#   based on the paths found in the ee_legacy_urls table of the configured database.
#
#   Author: Tyler Gannon <tyler@medallurgy.com>
#   Written: 2010 - 12 - 14
#   Updated: 2010 - 12 - 17 // Instead of writing a .htaccess file consisting
#             solely of rewrite directives, add rewrite directives into the 
#             .htaccess file that Drupal puts into the document root.
#
#################################################################

# filename='/var/www/webprod.pa.ucsf.edu/.htaccess'
filename='.htaccess'
user='ucsfdrupal'
password='08$cuR3'
dbhost='dbpa.ucsf.edu'
db='ucsf_drupal_prod'

tmpfile='/tmp/.htaccess.tmp'
begin_rules='BeginGeneratedRewriteRules'
end_rules='EndGeneratedRewriteRules'

#  First, remove all existing rewrite rules from the file, if there are any there.
if [ -n "`grep -n $begin_rules $filename`" ]; then sed -i".bak" "/$begin_rules/,/$end_rules/d" $filename ; fi

#  Determine the location of the RewriteEngine directive.

lines=`wc -l < $filename`
line_num=`grep -n RewriteEngine $filename`; line_num=(${line_num//\:/ });

# Get the first <line_num> lines from .htaccess into the temp file.
head -n $line_num $filename > $tmpfile

# Next, do the actual work
cat >> $tmpfile <<EOQ
  #$begin_rules
  #################################################################
  #
  #   mod_rewrite configuration
  #   
  #   DO NOT EDIT THIS INFO DIRECTLY.
  #   These rules are auto-generated by the script, /usr/sbin/mk_ucsf_legacy_rewrite_rules.sh,
  #   based on the paths found in the ee_legacy_urls table of the configured database.
  #
  #   Author: Tyler Gannon <tyler@medallurgy.com>
  #
  #   Last generated at `date`
  #
  #################################################################

EOQ
rewrite_rules_query="select concat('  RewriteRule ^', substring(old_path, 8+position('/' in replace(old_path, 'http://', ''))), '$ /', new_path, ' [NC,R=301,L]') from ee_legacy_urls;"
mysql -h $dbhost -p$password -u $user $db -sN -e "$rewrite_rules_query" >> $tmpfile

if [ $? -ne 0 ]; then 
  echo Encountered an error getting data from the database.  Exiting.
  exit 1
fi

cat >> $tmpfile <<EOQ
  #$end_rules
EOQ


# Now get the rest of the original .htaccess file
tail_lines=$(( lines - line_num ))
tail -n $tail_lines $filename >> $tmpfile

echo Successfully generated new `basename $filename` configuration.  Going to overwrite $filename.
echo "I will save a copy of the old `basename $filename` at /etc/httpd/conf.backup/"
if [ -d /etc/httpd/conf.backup ]; then echo; else mkdir /etc/httpd/conf.backup; fi
cp $filename "/etc/httpd/conf.backup/`basename $filename`.`date +%Y%m%d`"
cp $tmpfile $filename
echo 
exit 0

